version: '3.9'
services:
  frontend:
      build: ./
      container_name: app_frontend
      # depends_on:
      #   backend:
      #     condition: service_healthy
      environment:
          baseURL: "http://localhost:5000"
      ports:
        - 8081:80