
version: '3.9'

services:
  frontend:
    build: ./frontend
    restart: always
    container_name: app_frontend
    depends_on:
      - backend
    ports:
      - 4200:80

  backend:
    build:
      context: ./backend
    container_name: app_backend
    restart: always
    depends_on:
      - db_dev
    environment:
      - FLASK_APP=app/app.py
      - FLASK_DEBUG=1
      - MONGO_URI=mongodb+srv://admin:root@cluster0.hgpd8.mongodb.net/?retryWrites=true&w=majority
    ports:
      - 5000:8000