version: '3.9'

services:
  db_dev:
    container_name: mongodb
    image: mongo:5.0.10
    volumes:
      - .database:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root